Add Xlib.ext.dpms
Based on the documentation found here:
https://www.x.org/releases/X11R7.7/doc/xextproto/dpms.html

It basically works, however there are some known issues:
- Any rq.Request call (dpms_enable(), dpms_set_timeouts(),
  dpms_force_level()) only works if you call another rq.ReplyRequest
  function (dpms_get_version(), for example) afterwards. I tried to
  change them to use rq.ReplyRequest, but since they don't return
  anything they got stucked waiting for a response from X11.
- DPMSInfo doesn't work. I don't have a clue why, I receive the
  following error when trying to call dpms_info():

  ```
  $ cat playground.py
  from Xlib import display

  d = display.Display()
  print(d.dpms_info())

  $ python3 playground.py
  Traceback (most recent call last):
    File "playground.py", line 4, in <module>
      print(d.dpms_info())
    File "Xlib/display.py", line 225, in __getattr__
      return types.MethodType(function, self)
  TypeError: first argument must be callable
  ```

  So I decided to comment this function for now.